on:
  push:
    branches:
      - develop-main

jobs:
  deploy:
    name: Build & Test on Mainnet
    runs-on: ubuntu-latest
    environment: Juno1
    steps:
      - name: Install first
        run: sudo apt-get install grep jq chrony ca-certificates curl gnupg lsb-release expect -y
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      - run: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      - run: sudo apt-get update
      - name: Install docker
        run: sudo apt-get install docker-ce docker-ce-cli containerd.io
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0' # The Go version to download (if necessary) and use.
      - run: go version
      - uses: actions/checkout@v3
        with:
          repository: obi-wallet/proxy_contract
      - name: Install CosmWasm go pkg
        shell: bash
        run: |
          ./scripts/install_cosmwasm.sh
        env:
          GOPATH: "/home/runner/go"
      - name: Install Juno
        shell: bash
        run: |
          ./scripts/install_juno.sh
      - run: echo $(ls /home/runner/go/pkg/mod/github.com)
      - run: echo "ld library contains" && echo $(ls "$LD_LIBRARY_PATH")
        env:
          LD_LIBRARY_PATH: "/home/runner/go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.0.0/api"
      - run: echo "Gopath is $GOPATH"
        env: 
          GOPATH: "/home/runner/go"
      - name: Initialize Keys
        shell: bash
        run: |
          ./scripts/expect_wrapper.sh
        env:
          BASHTESTER: ${{ secrets.BASHTESTER }}
          BADTESTER: ${{ secrets.BADTESTER }}
          GOROOT: "/home/runner/goinstall/go"
          GOPATH: "/home/runner/go"
          GO111MODULE: "on"
          PATH: "$PATH:/home/runner/goinstall/go/bin:/home/runner/go/bin"
          LD_LIBRARY_PATH: "/home/runner/go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.0.0/api"
      - name: Deploy and Test
        shell: bash
        run: |
          ./scripts/deploy_proxy.sh
        env:
          GOROOT: "/home/runner/goinstall/go"
          GOPATH: "/home/runner/go"
          GO111MODULE: "on"
          PATH: "$PATH:/home/runner/goinstall/go/bin:/home/runner/go/bin"
          LD_LIBRARY_PATH: "/home/runner/go/pkg/mod/github.com/!cosm!wasm/wasmvm@v1.0.0/api"
          DENOM: ${{ secrets.DENOM }}
          CHAIN_ID: ${{ secrets.CHAIN_ID }}
          RPC: ${{ secrets.RPC }}